[package]
name = "wrclip"
version = "0.1.0"
authors = ["pkunk <pkunk.ab@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
os_pipe = "0.8"
tempfile = "3.1"
structopt = "0.2"
wayland-client = "0.23"
anyhow = "1.0"

[dev-dependencies]
rand = "0.7"
